version: "3.9"
services:
  postgres:
    image: "postgres:13.4-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: depression
      POSTGRES_PASSWORD: depression
      POSTGRES_DB: depression
